name: CI/CD al abrir pull/merge requests

on: push
  branches:
    - dev
    - main
    - qa
    
jobs:
  pre-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependencias
        run: npm install
        
      - name: Instalar Angular
        run: npm install -g @angular/cli

      - name: Testear Angular
        run: ng test
