name: CI/CD al cerrar pull/merge requests

on:
  push:
    branches:
      - dev
      - main
      - qa

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: angular-app-on-nginx

jobs:
  post-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Instalar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Iniciar sesión en GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar variables de entorno
        run: echo "REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Buildear y subir la imagen Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest